version: '3'

services:
  # Postgres
  db:
    container_name: postgresql
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
  redis:
    container_name: redis
    image: redis:7.2.1
    ports:
      - '6379:6379'
  rails:
    container_name: rails
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "rails_data:/rails"
    ports:
      - '3001:3000'
    depends_on:
      - db
      - redis

volumes:
  db_data:
  rails_data:
