# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.2.2
FROM ruby:$RUBY_VERSION-slim

# Rails app lives here
WORKDIR /rails

# Set development environment
# Set the rails master key for development build - don't do this in production!
ENV RAILS_MASTER_KEY="f10950908e60069c0ef3e0ccfbbf8c50" \
    RAILS_ENV="development"

# Update gems and bundler
RUN gem update --system --no-document && \
    gem install -N bundler

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential libpq-dev ca-certificates

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'production'
RUN bundle config set --local path 'vendor/bundle'
RUN bundle config set --local jobs '4'
RUN bundle install
# Copy application code
COPY . .

RUN cp local-cert/LocalCA.pem /usr/local/share/ca-certificates/LocalCA.crt
RUN update-ca-certificates

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start the server by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "ssl://0.0.0.0:3000?key=local-cert/api-local.youtubesharing.com.key&cert=local-cert/api-local.youtubesharing.com.crt"]
