FROM node:20.6.1-slim

# Install packages needed for deployment
WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y ca-certificates

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN cp LocalCA.pem /usr/local/share/ca-certificates/LocalCA.crt
RUN update-ca-certificates

EXPOSE 3000
CMD npm run start
