default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'youtube_sharing_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'youtube_sharing_test' } %>

production:
  <<: *default
  url: <%= ENV.fetch("DB_URL") { '' } %>
  database:  <%= ENV.fetch("DB_NAME") { 'youtube_sharing_prd' } %>
