default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  host: <%= ENV.fetch("DB_HOST") { '127.0.0.1' } %>
  timeout: 5000
  username: <%= ENV.fetch("DB_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'root' } %>

development:
  <<: *default
  database: youtube_sharing_dev

test:
  <<: *default
  database: youtube_sharing_test

production:
  <<: *default
  url: <%= ENV.fetch("DB_URL") { '' } %>
  database: youtube_sharing_prd
